service:
  name: mister-mail

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    excludeFiles: services/**/*.[spec.ts|map]
    includeModules:
      forceExclude:
        - "aws-sdk"
        - "@types/aws-lambda"
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  campaigns-table: ${self:service}-${self:custom.stage}
  ses-configuration-set: ${self:service}-${self:custom.stage}
  ses-email-events-topic: ${self:service}-${self:custom.stage}-ses-email-events-topic
  campaigns-topic: ${self:service}-${self:custom.stage}-campaigns-topic

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DYNAMODB_CAMPAIGN_TABLE: ${self:custom.campaigns-table}
    SNS_CAMPAIGNS_TOPIC:  ${self:custom.campaigns-topic}
    SES_EMAIL_EVENTS_TOPIC_ARN:  "arn:aws:sns:${self:custom.region}:#{AWS::AccountId}:${self:custom.ses-email-events-topic}"
    SES_CONFIGURATION_SET: ${self:custom.ses-configuration-set}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:custom.region}:#{AWS::AccountId}:table/${self:custom.campaigns-table}"

functions:
  create-campaign:
    handler: services/api/create-campaign.handler
    events:
      - http:
          method: post
          path: create
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: CognitoAuthorizer

  send-campaign-emails:
    handler: services/api/send-campaign-emails.handler
    events:
      - sns: ${self:custom.campaigns-topic}

  on-email-event:
    handler: services/api/on-email-event.handler
    events:
      - sns: ${self:custom.ses-email-events-topic}

resources:
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/ses.yml)}
