Resources:
  AppSyncDynamoDbServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppSyncDynamoDbServiceRole-${self:custom.stage}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
                - dynamodb.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncDynamoDbServicePolicy-${self:custom.stage}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:BatchWriteItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: ${self:custom.campaigns-table-arn}

  AppSyncLoggingServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppSyncLoggingServiceRole-${self:custom.stage}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncLoggingServicePolicy-${self:custom.stage}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "cloudwatch:*"
                Resource: "*"