Resources:
  SesConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: ${self:custom.ses-configuration-set}

  SesEventsTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: ${self:custom.ses-events-topic}

  # This is pretty obscure
  # The Serverless Framework transforms the name of lambda functions defined in serverless.yml
  #   * "-" is replaced by "Dash"
  #   * First letter is captitalized
  #   * "LambdaFunction" is added to the end
  # If in doubt check .serverless/serverless-state.json
  InvokeConfigureSesEvents:
    Type: Custom::LambdaInvocation
    DependsOn:
      - SesConfigurationSet
      - SesEventsTopic
      - ConfigureSesEventsLambdaFunction
    Properties:
      ServiceToken: !GetAtt ConfigureSesEventsLambdaFunction.Arn
      SesConfigurationSet: ${self:custom.ses-configuration-set}
      SnsTopicArn: !Ref SesEventsTopic