Resources:
  SesConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: ${self:custom.ses-configuration-set}

Outputs:
  SesConfigurationSet:
    Value:
      Ref: SesConfigurationSet
