projects:
  mister-mail-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/types.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: hd4vb6kyxvglbngwmgmupnav4m
        maxDepth: 2
extensions:
  amplify:
    version: 3
