on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Unit Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
