Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CognitoUserPool-${self:service}-${self:custom.stage}
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: CognitoUserPoolClient-${self:service}-${self:custom.stage}
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      GenerateSecret: false

Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool
    Export:
      Name: CognitoUserPoolId

  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: CognitoUserPoolClientId